version: 1.0.1
services:

  vn-work_database:
    container_name: vn-work_database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: demo_vn_work
    ports:
      - 3304:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - vn-work_network
    restart: always

  vn-work_redis:
    container_name: vn-work_redis
    image: redis
    ports:
      - 6374:6379
    volumes:
      - redis-data:/data
    networks:
      - vn-work_network
    restart: always

  backend:
    container_name: vn-work_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8884:8080
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vn-work_database:3306/demo_vn_work?createDatabaseIfNotExist=true
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - backend:/file:/file
    networks:
      - vn-work_network
    depends_on:
      - vn-work_database
      - vn-work_redis
    restart: always

volumes:
  database:
  backend:
  redis-data:
networks:
  vn-work_network:
    name: vn-work_network
    driver: bridge