logging:
  level:
    root: warn
    web: warn
#  file:
#    name: myapp.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
      max-history: 7
  pattern:
    dateformat: HH:mm:ss

openapi:
  service:
    api-docs: api-service
#    server: http://localhost:8080
#    title: API Service
#    version: 1.0.0

springdoc:
  swagger-ui:
    default-models-expand-depth: -1

spring:
  application:
    name: vn-work
  main:
    banner-mode: off
  devtools:
    add-properties: false

  datasource:
    url: jdbc:mysql://localhost:3306/demo_vn_work?createDatabaseIfNotExist=true
    username: root
    password: 123123

  jpa:
    hibernate:
      ddl-auto: update
    #    properties:
    #      hibernate.format_sql: true
#    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      repositories:
        enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    check-template-location: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: yourGmail@gmail.com
    #https://myaccount.google.com/apppasswords
    password: smtpPass
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#upload folder
upload:
  folder: ${UPLOAD_FOLDER:D://www/}

#jwt
JWT_SECRET_KEY: "IT_IS_NOT_LOOKING_GOOD_@#_IT_IS_NOT_LOOKING_GOOD"
